USE [hrms]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[YoutubeViews](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ViewsMonth] [nvarchar](50) NULL,
	[TotalViews] [int] NULL,
 CONSTRAINT [PK_YoutubeViews] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO